---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  labels:
    app: octodex
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octodex
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: octodex
    spec:
      containers:
      - name: aws-example-octodex
        image: 567792663880.dkr.ecr.us-east-2.amazonaws.com/example-eks:7d0fcd81acb8e271e20055356d4ae8ba2507b5f2
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
